### ISSUE TITLE
Some foreign error?

### ISSUE THREAD

**Issue by snaildos** [FlaringPhoenix/PteroManager#15]
0|index  | TypeError: Reduce of empty array with no initial value
0|index  |     at Array.reduce (<anonymous>)
0|index  |     at module.exports (/home/server/Ptero/events/ready.js:4:129)
0|index  |     at Client.emit (events.js:315:20)
0|index  |     at WebSocketManager.triggerClientReady (/home/server/Ptero/node_modules/discord.js/src/client/websocket/WebSocketManager.js:431:17)
0|index  |     at WebSocketManager.checkShardsReady (/home/server/Ptero/node_modules/discord.js/src/client/websocket/WebSocketManager.js:415:10)
0|index  |     at WebSocketShard.<anonymous> (/home/server/Ptero/node_modules/discord.js/src/client/websocket/WebSocketManager.js:197:14)
0|index  |     at WebSocketShard.emit (events.js:315:20)
0|index  |     at WebSocketShard.checkReady (/home/server/Ptero/node_modules/discord.js/src/client/websocket/WebSocketShard.js:475:12)
0|index  |     at Object.module.exports [as READY] (/home/server/Ptero/node_modules/discord.js/src/client/websocket/handlers/READY.js:20:9)
0|index  |     at WebSocketManager.handlePacket (/home/server/Ptero/node_modules/discord.js/src/client/websocket/WebSocketManager.js:384:31)

**Comment by snaildos** [comment]
Resolved.
