### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by MrQuackieDoes** [FlaringPhoenix/PteroManager#16]
The title says it all,
Do you by any chance use discord? So that I could contact u and get it fixed?

**Comment by MrQuackieDoes** [comment]
MongoServerSelectionError: connect ECONNREFUSED ::1:27017
    at Timeout._onTimeout (/home/container/node_modules/mongodb/lib/core/sdam/topology.js:438:30)
    at listOnTimeout (node:internal/timers:568:17)
    at processTimers (node:internal/timers:510:7) {
  reason: TopologyDescription {
    type: 'Unknown',
    setName: null,
    maxSetVersion: null,
    maxElectionId: null,
    servers: Map(1) { 'localhost:27017' => [ServerDescription] },
    stale: false,
    compatible: true,
    compatibilityError: null,
    logicalSessionTimeoutMinutes: null,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    commonWireVersion: null
  }
}
/home/container/node_modules/@josh-providers/mongo/src/index.js:44
    this.db = this.client.db(this.dbName).collection(this.collection);
                          ^

TypeError: Cannot read properties of undefined (reading 'db')
    at JoshProvider.init (/home/container/node_modules/@josh-providers/mongo/src/index.js:44:27)
    at runNextTicks (node:internal/process/task_queues:61:5)
    at listOnTimeout (node:internal/timers:536:9)
    at processTimers (node:internal/timers:510:7)

Node.js v17.3.0

This is the error how do I fix it?
